## Similar Setup using ESPHome 

esphome:
  name: amazonrefill
  platform: ESP8266
  board: d1_mini

switch:
  - platform: gpio
    name: "Amazon Refill Pump"
    pin: GPIO13
    icon: "mdi:water-pump"
    id: pump
    on_turn_on:
    - light.turn_on: light_pump
    - delay: 20000ms
    - switch.turn_off: pump
    on_turn_off:
    - light.turn_off: light_pump

output:
  - platform: gpio
    id: light_output
    pin:
      number: GPIO14

  - platform: gpio
    id: light_pump_output
    pin:
      number: GPIO16

binary_sensor:
  - platform: gpio
    device_class: moisture
    name: "Amazon Refill Level"
    pin:
      number: GPIO12
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.turn_on: light_refill
    on_release:
      then:
        - light.turn_off: light_refill

light:
  - platform: binary
    name: "Amazon Refill Status"
    output: light_pump_output
    id: light_pump

  - platform: binary
    name: "Amazon Refill Needed"
    output: light_output
    id: light_refill

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "WiFiID"
  password: "WiFiPassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AmazonRefill Fallback Hotspot"
    password: "some_random_pw"

captive_portal:
