- alias: Numpad A Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: A
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_a
  id: d6d6dc98551445f7a00190b9cbde8e89
- alias: Numpad B Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: B
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_b
  id: 4dbf709f7b404fa39267b5e54b7e161c
- alias: Numpad C Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: C
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_c
  id: 5d1a3bb85ee342d487d88c3816f17f51
- alias: Numpad D Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: D
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_d
  id: e5b6c106173241a3b435217469cfadfe
- alias: Numpad E Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: E
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_e
  id: 22b10124dddd4949bdb792f21208c0e4
- alias: Numpad F Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: F
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_f
  id: 5bf0ec9576aa48659359e08770aaaf66
- alias: Numpad G Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: G
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_g
  id: 96bdef9d38cd41ceb3975a540b7e97cd
- alias: Numpad H Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: H
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_h
  id: dd62eef255b441f6bd88de3b8fcafa99
- alias: Numpad I Toggle
  trigger:
  - platform: mqtt
    topic: numpad/reading/current
    payload: I
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.numpad_button_i
  id: 2c0c66c0a7d046f4856d2dbce254577c
- alias: Numpad A Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_a
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.table
- alias: Numpad B Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_b
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_overhead_light
    data:
      brightness: 200
      rgb_color:
      - 255
      - 236
      - 182
- alias: Numpad C Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_c
    from: 'off'
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.rickroll
- alias: Numpad D Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_d
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.desk
    data:
      brightness: 200
      rgb_color:
      - 255
      - 236
      - 182
- alias: Numpad E Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_e
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.entry_light
- alias: Numpad F Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_f
    from: 'off'
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.freshwater_feeder_script
- alias: Numpad G Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_g
    from: 'off'
    to: 'on'
  action:
  - service: notify.alexa_media
    data:
      data:
        type: tts
      target:
      - media_player.gabe_s_alexa
      message: You Shouldn't have pressed that button.
- alias: Numpad I Automation On
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_i
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.desk_overhead
    data:
      brightness: 200
      rgb_color:
      - 255
      - 236
      - 182
- alias: Numpad A Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_a
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.table
- alias: Numpad B Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_b
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.kitchen_overhead_light
- alias: Numpad C Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_c
    from: 'on'
    to: 'off'
  action:
  - service: shell_command.volumio_pause
- alias: Numpad D Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_d
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.desk
- alias: Numpad E Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_e
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.entry_light
- alias: Numpad F Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_f
    from: 'on'
    to: 'off'
  action:
  - service: script.turn_on
    entity_id: script.freshwater_feeder_script
- alias: Numpad G Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_g
    from: 'on'
    to: 'off'
  action:
  - service: notify.alexa_media
    data:
      data:
        type: tts
      target:
      - media_player.gabe_s_alexa
      message: I've just launched the missiles. This room will self destruct."
- alias: Numpad I Automation Off
  trigger:
  - platform: state
    entity_id: input_boolean.numpad_button_i
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.desk_overhead
