# Add this to your binary_sensor.yaml file in Home Assistant

- platform: mqtt
  name: Notify Motion
  state_topic: 'notifyscreen/motion'
  payload_on: "MOTION"
  payload_off: "NO MOTION"
  device_class: motion
  expire_after: 60
  off_delay: 60
