#ESPHome Code - works on ESP8266, nodeMCU, etc.

esphome:
  name: bottlescale
  platform: ESP8266
  board: nodemcuv2  #check ESPHome docs for your board

light:
  - platform: binary
    name: "Bottle Scale LED Green"
    output: led_green_output
  - platform: binary
    name: "Bottle Scale LED Yellow"
    output: led_yellow_output
  - platform: binary
    name: "Bottle Scale LED White"
    output: led_white_output

output:
  - id: led_green_output
    platform: gpio
    pin: D8
  - id: led_yellow_output
    platform: gpio
    pin: D1
  - id: led_white_output
    platform: gpio
    pin: D4

sensor:
  - platform: hx711
    name: "Bottle Scale Value"
    dout_pin: D6
    clk_pin: D5
    gain: 128
    update_interval: 4s
    filters:
      - calibrate_linear:
          - -474335 -> 0.0
          - -447597 -> 2.0
          - -433614 -> 3.0
    unit_of_measurement: oz
    accuracy_decimals: 3
    on_value_range:
      - above: 1.46
        then:
          - output.turn_on:
              id: led_white_output
      - below: 1.45
        then:
          - output.turn_off:
              id: led_white_output

binary_sensor:
  - platform: gpio
    device_class: lock
    name: "Bottle Scale Full Button"
    pin:
      number: D3
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - output.turn_on:
            id: led_yellow_output
    on_release:
      then:
        - output.turn_off:
            id: led_yellow_output

  - platform: gpio
    device_class: lock
    name: "Bottle Scale Empty Button"
    pin:
      number: D2
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - output.turn_on:
            id: led_green_output
    on_release:
      then:
        - output.turn_off:
            id: led_green_output

# Enable loggicccng
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "YourWIFINetwork"
  password: "YourWIFIPassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BottleScale Fallback Hotspot"
    password: "xxxxxxx"

captive_portal:
